CREATE TABLE [dbo].[641604] (
    [Column 0]                                                                     VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Sydney ;]       VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of NSW ;]  VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Melbourne ;]    VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of Vic  ;] VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Brisbane ;]     VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of Qld  ;] VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Adelaide ;]     VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of SA ;]   VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Perth ;]        VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of WA ;]   VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Hobart ;]       VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of Tas  ;] VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Darwin ;]       VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Rest of NT ;]   VARCHAR (50) NULL,
    [Median Price of Established House Transfers (Unstratified) ;  Canberra ;]     VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Sydney ;]       VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of NSW ;]  VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Melbourne ;]    VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of Vic  ;] VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Brisbane ;]     VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of Qld  ;] VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Adelaide ;]     VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of SA ;]   VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Perth ;]        VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of WA ;]   VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Hobart ;]       VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of Tas  ;] VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Darwin ;]       VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Rest of NT ;]   VARCHAR (50) NULL,
    [Median Price of Attached Dwelling Transfers (Unstratified) ;  Canberra ;]     VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Sydney ;]                            VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of NSW ;]                       VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Melbourne ;]                         VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of Vic  ;]                      VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Brisbane ;]                          VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of Qld  ;]                      VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Adelaide ;]                          VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of SA ;]                        VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Perth ;]                             VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of WA ;]                        VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Hobart ;]                            VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of Tas  ;]                      VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Darwin ;]                            VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Rest of NT ;]                        VARCHAR (50) NULL,
    [Number of Established House Transfers ;  Canberra ;]                          VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Sydney ;]                            VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of NSW ;]                       VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Melbourne ;]                         VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of Vic  ;]                      VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Brisbane ;]                          VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of Qld  ;]                      VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Adelaide ;]                          VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of SA ;]                        VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Perth ;]                             VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of WA ;]                        VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Hobart ;]                            VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of Tas  ;]                      VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Darwin ;]                            VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Rest of NT ;]                        VARCHAR (50) NULL,
    [Number of Attached Dwelling Transfers ;  Canberra ;]                          VARCHAR (50) NULL
);

