CREATE TABLE [Staging].[AFR_ASXIndices_Weekly_Raw] (
    [RunID]              INT           NULL,
    [SystemID]           INT           NULL,
    [FileID]             INT           NULL,
    [Code]               VARCHAR (50)  NULL,
    [Description]        VARCHAR (50)  NULL,
    [Day1]               VARCHAR (50)  NULL,
    [Day2]               VARCHAR (50)  NULL,
    [Day3]               VARCHAR (50)  NULL,
    [Day4]               VARCHAR (50)  NULL,
    [Day5]               VARCHAR (50)  NULL,
    [Day High]           VARCHAR (50)  NULL,
    [Day Low]            VARCHAR (50)  NULL,
    [Day Var +/-]        VARCHAR (50)  NULL,
    [Day %]              VARCHAR (50)  NULL,
    [Week High]          VARCHAR (50)  NULL,
    [Week Low]           VARCHAR (50)  NULL,
    [Week +/-]           VARCHAR (50)  NULL,
    [Week %]             VARCHAR (50)  NULL,
    [Month High]         VARCHAR (50)  NULL,
    [Month Low]          VARCHAR (50)  NULL,
    [Month +/-]          VARCHAR (50)  NULL,
    [Month %]            VARCHAR (50)  NULL,
    [YTD High]           VARCHAR (50)  NULL,
    [YTD Low]            VARCHAR (50)  NULL,
    [YTD +/-]            VARCHAR (255) NULL,
    [YTD %]              VARCHAR (255) NULL,
    [52 Week High]       VARCHAR (255) NULL,
    [52 Week Low]        VARCHAR (255) NULL,
    [52 Week +/-]        VARCHAR (50)  NULL,
    [52 Week %]          VARCHAR (50)  NULL,
    [Accum_Day1]         VARCHAR (50)  NULL,
    [Accum_Day2]         VARCHAR (50)  NULL,
    [Accum_Day3]         VARCHAR (50)  NULL,
    [Accum_Day4]         VARCHAR (50)  NULL,
    [Accum_Day5]         VARCHAR (50)  NULL,
    [Accum_Week High]    VARCHAR (50)  NULL,
    [Accum_Week Low]     VARCHAR (50)  NULL,
    [Accum_Week +/-]     VARCHAR (50)  NULL,
    [Accum_Week %]       VARCHAR (50)  NULL,
    [Accum_Month High]   VARCHAR (50)  NULL,
    [Accum_Month Low]    VARCHAR (50)  NULL,
    [Accum_Month +/-]    VARCHAR (50)  NULL,
    [Accum_Month %]      VARCHAR (50)  NULL,
    [Accum_YTD High]     VARCHAR (50)  NULL,
    [Accum_YTD Low]      VARCHAR (50)  NULL,
    [Accum_YTD +/-]      VARCHAR (50)  NULL,
    [Accum_YTD %]        VARCHAR (50)  NULL,
    [Accum_52 Week High] VARCHAR (50)  NULL,
    [Accum_52 Week Low]  VARCHAR (50)  NULL,
    [Accum_52 Week +/-]  VARCHAR (50)  NULL,
    [Accum_52 Week %]    VARCHAR (50)  NULL
);

