CREATE TABLE [Staging].[RBA_EmploymentData_Daily_Raw] (
    [RunID]                                INT           NULL,
    [SystemID]                             INT           NULL,
    [FileID]                               INT           NULL,
    [Title]                                VARCHAR (100) NULL,
    [Labour force]                         VARCHAR (100) NULL,
    [Participation rate]                   VARCHAR (100) NULL,
    [Part-time employment]                 VARCHAR (100) NULL,
    [Full-time employment]                 VARCHAR (100) NULL,
    [Employment]                           VARCHAR (100) NULL,
    [Year-ended employment growth]         VARCHAR (100) NULL,
    [Year-ended employment trend growth]   VARCHAR (100) NULL,
    [Employment to population ratio]       VARCHAR (100) NULL,
    [Unemployment]                         VARCHAR (100) NULL,
    [Unemployment rate]                    VARCHAR (100) NULL,
    [Unemployment rate trend]              VARCHAR (100) NULL,
    [Hours worked]                         VARCHAR (100) NULL,
    [Hours worked trend]                   VARCHAR (100) NULL,
    [Year-ended hours worked trend growth] VARCHAR (100) NULL,
    [Average hours worked trend]           VARCHAR (100) NULL,
    [Job vacancies]                        VARCHAR (100) NULL,
    [Private sector job vacancies]         VARCHAR (100) NULL,
    [Vacancies to labour force ratio ]     VARCHAR (100) NULL
);

